name: Read Helm Values
branding:
  icon: arrow-down-left
  color: gray-dark
description:
  Given a list of values.yaml files, it will read specified expressions from the merged result to the `json` output
inputs:
  working-directory:
    description: Base directory for values files
    required: false
  values:
    description: List of values files, separated by newline
    required: true
  output:
    description: Key-values list of variables to read, format is `key=.yq.expression`, each pair is on new line
    required: true
outputs:
  json:
    value: ${{ steps.extract.outputs }}
    description: JSON object with desired variables
runs:
  using: docker
  image: ./Dockerfile
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.values }}
    - ${{ inputs.output }}
